# ==============================
# Aplicação
# ==============================
spring.application.name=reservvo

# ==============================
# Banco de Dados (PostgreSQL)
# ==============================
spring.datasource.url=jdbc:postgresql://localhost:5432/reservvo
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# ==============================
# JPA / Hibernate
# ==============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# ==============================
# Redis
# ==============================
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}

# ==============================
# AWS
# ==============================
aws.region=${AWS_REGION:sa-east-1}
aws.ses.from=noreply@reservvo.com
aws.ses.from-name=Reservvo

# ==============================
# Logs
# ==============================
logging.level.root=INFO
logging.level.com.odgiedev.reservvo=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG

# ==============================
# Server
# ==============================
server.port=8080