# Aplicação
spring.application.name=reservvo
spring.profiles.active=${SPRING_PROFILE:dev}

# Server
server.port=8080

# Banco de Dados (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/reservvo}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.repositories.enabled=false

# AWS
aws.region=${AWS_REGION:sa-east-1}
aws.ses.from=${AWS_FROM_EMAIL}
aws.ses.from-name=Reservvo
aws.access-key-id=${AWS_ACCESS_KEY_ID}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY}

# Logs
logging.level.root=INFO
logging.level.com.odgiedev.reservvo=DEBUG
logging.level.org.springframework.security=INFO
#logging.level.org.hibernate.SQL=DEBUG

# Suppress warnings:
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR
logging.level.org.springdoc.core.events.SpringDocAppInitializer=ERROR
logging.level.io.netty.resolver.dns.DnsServerAddressStreamProviders=ERROR

# Swagger UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui
springdoc.swagger-ui.operationsSorter=method